In [3]:
import numpy as np
import math

In [15]:
a = np.array(([1,2,3,4],[2,3,4,5]))
print(a.ndim)

2


In [18]:
a.shape

(2, 4)

In [19]:
a.dtype

dtype('int64')

In [20]:
a.dtype.name

'int64'

In [26]:
c = np.zeros((3,3))
d = np.ones((3,3))
d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.random.rand(3,3)

array([[0.65053804, 0.40242941, 0.21571893],
       [0.17327006, 0.24010791, 0.9669253 ],
       [0.02392189, 0.69980049, 0.12551428]])

In [31]:
np.arange(2, 20, 3)

array([ 2,  5,  8, 11, 14, 17])

In [32]:
np.linspace(3, 20, 30)

array([ 3.        ,  3.5862069 ,  4.17241379,  4.75862069,  5.34482759,
        5.93103448,  6.51724138,  7.10344828,  7.68965517,  8.27586207,
        8.86206897,  9.44827586, 10.03448276, 10.62068966, 11.20689655,
       11.79310345, 12.37931034, 12.96551724, 13.55172414, 14.13793103,
       14.72413793, 15.31034483, 15.89655172, 16.48275862, 17.06896552,
       17.65517241, 18.24137931, 18.82758621, 19.4137931 , 20.        ])

## Array Operation

In [38]:
a = np.array([2,3,4,5])
b = np.array([1, 1, 1, 1])

c = a + b
print(c)

a * b

[3 4 5 6]


array([2, 3, 4, 5])

In [40]:
c > 4

array([False, False,  True,  True])

In [41]:
A = np.array([[1, 2],[3, 4]])
B = np.array(([2, 2],[2, 2]))

print(A*B)
print(A@B)

[[2 4]
 [6 8]]
[[ 6  6]
 [14 14]]


In [44]:
a = np.arange(2, 11).reshape(3, 3)
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])